version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    restart: always
    env_file:
      - ./auth-server/.env 
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/authdb?authSource=admin
      JWT_SECRET: "NS$@HTD$@UJ%BNS&FFAS@$@asid2@&%S"
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server:/app
    command: npm run start:dev

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    restart: always
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/eventdb?authSource=admin
    depends_on:
      - mongo
    ports:
      - "3002:3002"
    volumes:
      - ./event-server:/app
    command: npm run start:dev

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    restart: always
    env_file:
      - ./gateway-server/.env 
    environment:
      AUTH_URL: http://auth-server:3001
      EVENT_URL: http://event-server:3002
      JWT_SECRET: "NS$@HTD$@UJ%BNS&FFAS@$@asid2@&%S"
    depends_on:
      - auth-server
      - event-server
    ports:
      - "3000:3000"
    volumes:
      - ./gateway-server:/app
    command: npm run start:dev

volumes:
  mongo-data:
